# Generated by Django 4.2.7 on 2023-11-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page_info',
            name='home_page_intro_sub_title',
            field=models.TextField(null=True),
        ),
    ]
