# Generated by Django 4.2.7 on 2023-11-24 08:03

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_about_us_page_info_about_us_introduction_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='news')),
                ('title', models.CharField(max_length=200)),
                ('headline', models.TextField()),
                ('detail', tinymce.models.HTMLField()),
            ],
        ),
    ]
