# Generated by Django 4.2.7 on 2023-11-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='News_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=200)),
                ('user_photo', models.ImageField(default='default.jpg', upload_to='users')),
                ('comment', models.TextField()),
                ('date_commented', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hub.new')),
            ],
        ),
    ]
