# Generated by Django 4.2.7 on 2023-11-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_new_date_posted_news_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us_page_info',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact_us_page_info',
            name='contact_fax',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact_us_page_info',
            name='contact_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact_us_page_info',
            name='contact_phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
