# Generated by Django 4.2.7 on 2023-11-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_contact_us_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us_page_info',
            name='background_image',
            field=models.ImageField(default='default.jpg', upload_to='settings'),
        ),
        migrations.AddField(
            model_name='contact_us_page_info',
            name='background_image',
            field=models.ImageField(default='default.jpg', upload_to='settings'),
        ),
        migrations.AddField(
            model_name='home_page_info',
            name='background_image',
            field=models.ImageField(default='default.jpg', upload_to='settings'),
        ),
    ]
