# Generated by Django 4.2.7 on 2023-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_about_us_page_info_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page_info',
            name='home_page_map_image',
            field=models.ImageField(default='default.jpg', upload_to='settings'),
        ),
    ]
